POST http://localhost:3001/api/gigs HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVkb2UiLCJpZCI6IjY3Zjc1NzE0ZDFiZTliY2ZjNDBmMGUzOCIsImlhdCI6MTc0NDI2Mjk1MH0.5ttcKSVN8k78AQdfQy9IfS27duWx_mVdbtdmh1ecS9I
content-type: application/json

{
    "name": "Test",
      "artist": "Test",
      "add_image": "/public/zemfira.png",
      "description": "description",
      "gig_date": "2025-03-18",
      "time": "18:00",
      "address": "Hämeenkatu 1, 33300",
      "city": "Tampere",
      "ticket_sale_link": "https://www.lippu.fi/",
      "genre": "rock",
      "artist_link": "huskyrescue.fi",
      "rate": 5,
      "user_id": "67dd30d4add91a9fad155069"
} 